{% set name = "llama-cloud" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_cloud-{{ version }}.tar.gz
  sha256: 8ce1db36754a6a46c8511561dbc040a2e89ba4ca1cf4edfb6ce382a5240f6cb6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0
    - pydantic >=1.10
    - httpx >=0.20.0

test:
  imports:
    - llama_cloud
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Turn your enterprise data into production-ready LLM applications
  home: https://cloud.llamaindex.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
