{% set name = "llama-cloud" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_cloud-{{ version }}.tar.gz
  sha256: d3b324c36cbbae5fcf0f2a17af521fc10ae0d6bdaab54b704e61818fe23d421e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio
    - typing_extensions >=4.10,<5
    - certifi >=2024.7.4
    - python >={{ python_min }},<4.0
    - pydantic >=1.9.0,<3
    - httpx >=0.23.0,<1

test:
  imports:
    - llama_cloud
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Turn your enterprise data into production-ready LLM applications
  home: https://cloud.llamaindex.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
