{% set name = "llama-cloud" %}
{% set version = "0.1.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_cloud-{{ version }}.tar.gz
  sha256: dcb741b779e3e740cd64928cfffc8ef70ed0e9bae9ef26acbe1d7e32aa737bdc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - certifi >=2024.7.4
    - python >={{ python_min }},<4.0
    - pydantic >=1.10
    - httpx >=0.20.0

test:
  imports:
    - llama_cloud
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Turn your enterprise data into production-ready LLM applications
  home: https://cloud.llamaindex.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
